### ISSUE TITLE
build: update http and dart

### ISSUE THREAD

**Issue by Feichtmeier** [tomassasovsky/radio-browser-api.dart#2]
Hi 👋 

If you have time it would be nice if you could update http and thus dart so I can update http inside musicpod 😸 

Thanks in advance and best regards and thank you again for this nice package!

**Comment by tomassasovsky** [comment]
Just published the new version! https://pub.dev/packages/radio_browser_api Thanks for opening the issue!

**Comment by Feichtmeier** [comment]
:dash: :zap: wow this was fast
did you automated some things there? :O :+1:

**Comment by tomassasovsky** [comment]
I haven't been using Flutter or Dart lately, so I didn't even notice Flutter upgraded to Dart 3.0 in the stable branch haha; I tend to use the VSCode extension [Version Lens](https://marketplace.visualstudio.com/items?itemName=pflannery.vscode-versionlens) for this type of thing, and that makes it way easier to get everything up to date 😎

Thanks again for noticing and reporting this issue, always good to hear from members of the community 💙!
