### ISSUE TITLE
fix: ClickStation has a cast error

### ISSUE THREAD

**Issue by Feichtmeier** [tomassasovsky/radio-browser-api.dart#9]
When using the clickStation method, this error is thrown
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'String' is not a subtype of type 'Map<dynamic, dynamic>' in type cast
#0      RadioBrowserApi.clickStation (package:radio_browser_api/src/radio_browser_api.dart:574:56)
<asynchronous suspension>
```

it calls this code

```dart
Future<StationClickCounter> clickStation({
    /// The UUID of the station that was clicked.
    required String uuid,
  }) async {
    assert(
      uuid.isNotEmpty,
      'Invalid uuids value; must contain at least one UUID',
    );

    final uri = Uri(
      scheme: 'https',
      host: host,
      path: '/json/url/$uuid',
    );

    final response = await http.get(uri);
    return StationClickCounter.fromJson((response.body as Map).cast());
  }
``` 

--->

```dart
 /// {@macro station_click_counter}
  factory StationClickCounter.fromJson(Map<String, dynamic> json) =>
      _$StationClickCounterFromJson(json);
``` 

--->

```dart
StationClickCounter _$StationClickCounterFromJson(Map<String, dynamic> json) =>
    StationClickCounter(
      ok: json['ok'] as bool,
      message: json['message'] as String,
      stationUUID: json['stationuuid'] as int,
      name: json['name'] as String,
      url: json['url'] as String,
    );
```

**Comment by tomassasovsky** [comment]
Working fine with UUID: 9617a958-0601-11e8-ae97-52543be04c81
![image](https://github.com/tomassasovsky/radio-browser-api.dart/assets/63405252/86df14c1-c574-4558-9349-c22aa28d1527)

This must occur when you call this function with an invalid (or unsynced) station UUID, as shown here:
![image](https://github.com/tomassasovsky/radio-browser-api.dart/assets/63405252/c5ac1099-750f-4825-81b4-ca00bfe39a3f)

This could probably use better error handling though. I'll work on that whenever I free up from work a little bit, and I'll keep you posted. Thanks!

**Comment by Feichtmeier** [comment]
> 9617a958-0601-11e8-ae97-52543be04c81

Thanks for your answer!
Sadly not, I copy pasted the exact UUID from you into a test call and the same exceptions happens :(

**Comment by tomassasovsky** [comment]
Okay, that should fix it. Please update to `2.0.0` and let me know if anything else is wrong!

**Comment by Feichtmeier** [comment]
Thank you very much @tomassasovsky :) worked 👍

**Comment by Feichtmeier** [comment]
@tomassasovsky 
sometimes an exception is thrown when using clickStation

``` 
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unexpected character (at character 1)
<html>
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1376:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1243:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:908:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
#4      JsonDecoder.convert (dart:convert/json.dart:610:36)
#5      JsonCodec.decode (dart:convert/json.dart:216:41)
#6      jsonDecode (dart:convert/json.dart:155:10)
#7      RadioBrowserApi.clickStation (package:radio_browser_api/src/radio_browser_api.dart:574:22)
<asynchronous suspension>
#8      RadioService.clickStation (package:musicpod/src/radio/radio_service.dart:116:5)
<asynchronous suspension>
#9      RadioModel.clickStation (package:musicpod/src/radio/radio_model.dart:89:14)
<asynchronous suspension>
``` 

but I couldnt yet find a pattern when this happening. Will keep you updated
Edit: I think it happens when this functions is used quite often in a row

**Comment by tomassasovsky** [comment]
Huh, very weird - please do give an update if you find any way to reproduce it. Any test code snippets are always appreciated. You might also want to wrap your call to the API with the `retry` function from [this](https://pub.dev/packages/retry) package.

**Comment by tomassasovsky** [comment]
@Feichtmeier I just checked the API reference for this endpoint. It says "Every call to this endpoint from the same IP address and for the same station only gets counted once per day", so it might have to do with that.

See more: https://docs.radio-browser.info/#station-click-counter

**Comment by Feichtmeier** [comment]
> @Feichtmeier I just checked the API reference for this endpoint. It says "Every call to this endpoint from the same IP address and for the same station only gets counted once per day", so it might have to do with that.
> 
> See more: https://docs.radio-browser.info/#station-click-counter

Ahhh that must be it :) thanks! 
I'll digest this in the app then
Thanks for your time!
